version: "2.4"
services:

    alpine:
      image: deathwalker66/debian
      container_name: DEV.Debian
      volumes:
          - COM:/COM
          - ./SCP:/SCP
          - ./INI/supervisor.conf:/etc/supervisor/supervisord.conf
          - ./INI/startup.conf:/etc/supervisor/conf.d/startup.conf
      ports:
       - "30322:22"
      network_mode: catnet
      env_file: .env

volumes:
   COM:
        driver_opts:
          type: none
          device: /mnt/Dock/Com
          o: bind      