[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=1MB
logfile_backups=2
pidfile=/var/run/supervisord.pid
loglevel=info
user=root

[include]
files = /etc/supervisor/conf.d/*.conf